version: '3.7'
services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - mongo-configdb:/data/configdb

  backend:
    depends_on:
      - mongo
    image: custom/backend-police
    ports:
      - "8000:8000"
    volumes:
      - .:/opt
    links:
      - mongo

volumes:
  mongo-data:
  mongo-configdb: